---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ibm-entitlement-key
  namespace: tools
spec:
  encryptedData:
    .dockerconfigjson: AgB+DwdV5uX6jrDA73Sdb3W+8WuzeD/03AAOQhRZ6hJpWZPyxuJncc8wzXtfkt48urwfg/tK1rHFAG8VOtyQnInZe3R0NuOFELdWZ9u8CkuN01PzWU/WwLPpWtlXDx76If4Mb1rHyK4KR6IqAi8OZJzZxis0863IZc26cN9KYPWmgzVEkc6JVCdvEuJWM/oT9O9IHOhA6NeZ6khw3YySAgIWK8TOqrvi/zraF+OOx53khy52syVtwVityuiaZk7vx1riC2DNfCcRjyCZz+sWYamTkPL1qKzqBGkGxgCRHwNMmP4U7CAAPe625VS0DmBOY/lN5ORcFzpI9QBsiZZ1+xx7/+CRAQfPnq4S5RvZfDzMlpRZqsv/gL+fqB28b5SYb7UqVNnDmGQ8/KXRrEF4HUtJ8MMJWFBcOcDTjEc9vgiw/m8Z8ReOTw6dtN9qj10q3tAg/cZtLu1sdvvHmyxPglppupvsRwaoos7kWEJg/G8sMz3WmUnI3oO0Ta//x5g2Sppt+e1C9LvF8cEGe0ij4GiMMy/cFNDRfch3YYPZGqEG02yEQAMgZidgynckg+24cUuiekvmqJuKmBLS8quwU7Bq7tWC5I1Ed9xd4uz6P5d4SHE4755x0Q6mHo3tLER/3tAOY4LBoFAjam4LHzKGU/8+1U1u7GET6ZBQy2Lf2YvFqgLWZzxVQRjWJ9Qx8sGxQ22QwA10ekZl3f79BKU44z3iFTDDE9Oc9CHbGaYrc+4QeK2XXwoTLgeaACv52wXJeSQALUsdCZUC5UtDd/9uky6rTjh3cqPldoOuC2WeaYbuFq4j/xosRKg8hrkgtcpk8FUqKghYg3slqBzPxSjP1hjTeqYm6C1o3eReSFPw0dTgKokjQyyxIHxo1yK0x3q3sve2HK5Il8y7yy6M0UwPvhAT0c0BG3P/R0s/R+65MXWqSfnT2fGtee1AAbuDUxrGkJNg6ssDks96gr2X5ZMGHqmslhxJDFLrK59u2IE6vMxVOeMIJeIA90k/LrFYix8l+w5U5c9V55K2XuO82+ovZ2z0XQ+nmYxyTX7oIMsbmDDaBdmD3brByFnEfo667Tj3ch/DfzLrqpTFDOUbsw6QF0P1WE6GgbXQhl9pbS436E3ReJKB7BrO8f2WtxT1B5pAdxAN1nY3riMOzB5RWob4on4WJfvQM5tfqwWzu9eFzLpHQvzVscd9Rudn4Y0NB/TxxXUBk6OiXdJqtCHtD2zYXhCvLNP8oMEGGb+QRE/TF/oMZhgJUEp+bCKrN99BeQhHxCk35VNJQRbYcLKVFYn5W7gxiZzWvyQ2omGAMuKUoycTZXwngh3yurqzN5r0hu/9LLfy6Ehdwytrd62R0AuzXtJC1WKIYpJWUIr0LUDiguowVJbSjBS2
  template:
    metadata:
      creationTimestamp: null
      name: ibm-entitlement-key
      namespace: tools
    type: kubernetes.io/dockerconfigjson
